### PR TITLE
Don't run Codacy Analysis w/o token

### PR DESCRIPTION
**Pull request by szepeviktor**
Pull Requests will not have that token.

### CODE REVIEW

**Comment by szepeviktor** [comment]
kép

**Comment by MathiasReker** [comment]
I get this error, if I try to merge it. 🙂

**Comment by MathiasReker** [comment]
Thank you @szepeviktor !

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by szepeviktor** [comment]
I see that these two steps are skipped on the develop branch.
https://github.com/MathiasReker/php-script-cache/actions/runs/3367726431/jobs/5585481764
Could it be that the token is not set?
Does open-source projects need a token at all?

**Pull request merged**
